### ISSUE TITLE
Wix MVP

### ISSUE THREAD

**Issue by pento** [pento/free-as-in-speech#6]
Splitting this off from #2.

### Popup Page

The popup page is the primary UI for interacting with the extension.

- [x] Fill out the page with information about what will be exported.
- [x] After the Export button is clicked, show progress information.
- [x] Add translation for the strings.

### Wix Extractor API

This task is focussed on making a generic interface for adding support for extracting from additional Wix apps. This makes it much easier to expand and maintain the library of "app extractors".

- [x] Determine which apps are enabled on the current site.
- [x] Add the ability for extractors to report progress.

There are some additional parts of this API which would be nice to have, but not necessary for an MVP.

- [x] Add the ability to store extracted data in local storage, and resume extraction. Particularly useful to recover from internet outages or browser crashes.

### Blog

- [x] Add support for more blocks than just paragraphs.
- [x] Add support for paging through posts/categories/tags.
- [x] Add media support.

**Comment by pento** [comment]
Since the last item in this list has been done, I'm going to close this issue.

There was one remaining item when doesn't need to be in the MVP, I split that off into #39.
